import { useQuery } from "@tanstack/react-query";
import { downloadsApi } from "@/lib/api/downloads";

export interface SubtitleTrack {
  id: string;
  name: string;
  ext: string;
  isAutoGenerated: boolean;
}

export const useListSubtitles = (url: string, enabled: boolean = true) =>
  useQuery<SubtitleTrack[]>({
    queryKey: ["subtitles", "list", url] as const,
    queryFn: () => downloadsApi.listSubtitles(url),
    enabled: enabled && url.length > 0,
    staleTime: 1000 * 60 * 5 // 5 minutes
  });
