import { create } from "zustand";
import type { SubtitleType, SubtitleLanguage } from "@/features/subtitle-options/types";

export interface SubtitleState {
  subtitleType: SubtitleType;
  languages: SubtitleLanguage[];
  includeAutoGenerated: boolean;
}

export interface SubtitleActions {
  setSubtitleType: (type: SubtitleType) => void;
  setLanguages: (languages: SubtitleLanguage[]) => void;
  addLanguage: (language: SubtitleLanguage) => void;
  removeLanguage: (language: SubtitleLanguage) => void;
  setIncludeAutoGenerated: (include: boolean) => void;
  reset: () => void;
}

export type SubtitleStore = SubtitleState & SubtitleActions;

const initialState: SubtitleState = {
  subtitleType: "none",
  languages: ["en"],
  includeAutoGenerated: false
};

export const useSubtitleStore = create<SubtitleStore>((set) => ({
  ...initialState,

  setSubtitleType: (type: SubtitleType) => set({ subtitleType: type }),

  setLanguages: (languages: SubtitleLanguage[]) => set({ languages }),

  addLanguage: (language: SubtitleLanguage) =>
    set((state) => {
      if (!state.languages.includes(language)) {
        return { languages: [...state.languages, language] };
      }
      return state;
    }),

  removeLanguage: (language: SubtitleLanguage) =>
    set((state) => ({
      languages: state.languages.filter((l) => l !== language)
    })),

  setIncludeAutoGenerated: (include: boolean) => set({ includeAutoGenerated: include }),

  reset: () => set(initialState)
}));
