import { useShallow } from "zustand/react/shallow";
import type { SubtitleStore } from "./subtitle-options.store";
import { useSubtitleStore } from "./subtitle-options.store";

const selectSubtitleState = (state: SubtitleStore) => ({
  subtitleType: state.subtitleType,
  languages: state.languages,
  includeAutoGenerated: state.includeAutoGenerated
});

const selectSubtitleActions = (state: SubtitleStore) => ({
  setSubtitleType: state.setSubtitleType,
  setLanguages: state.setLanguages,
  addLanguage: state.addLanguage,
  removeLanguage: state.removeLanguage,
  setIncludeAutoGenerated: state.setIncludeAutoGenerated,
  reset: state.reset
});

export const useSubtitleState = () => useSubtitleStore(useShallow(selectSubtitleState));
export const useSubtitleActions = () => useSubtitleStore(useShallow(selectSubtitleActions));

export const selectSubtitleType = (state: SubtitleStore) => state.subtitleType;
export const selectSubtitleLanguages = (state: SubtitleStore) => state.languages;
export const selectSubtitleIncludeAutoGenerated = (state: SubtitleStore) => state.includeAutoGenerated;
