import {
  useSubtitleState,
  useSubtitleActions
} from "@/stores/subtitle-options/subtitle-options.selectors";
import { Label } from "@vault/ui/components/label";
import { Switch } from "@vault/ui/components/switch";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue
} from "@vault/ui/components/select";
import type { SubtitleLanguage, SubtitleType } from "@/features/subtitle-options/types";

const SUBTITLE_LANGUAGES: { value: SubtitleLanguage; label: string }[] = [
  { value: "en", label: "English" },
  { value: "es", label: "Spanish" },
  { value: "fr", label: "French" },
  { value: "de", label: "German" },
  { value: "ja", label: "Japanese" },
  { value: "zh", label: "Chinese" },
  { value: "auto", label: "Auto-Generated" }
];

export const SubtitleOptions = () => {
  const { subtitleType, languages, includeAutoGenerated } = useSubtitleState();
  const { setSubtitleType, setLanguages, setIncludeAutoGenerated } = useSubtitleActions();

  const handleSubtitleTypeChange = (value: SubtitleType | null) => {
    if (!value) return;
    setSubtitleType(value);
  };

  const handleLanguageChange = (value: SubtitleLanguage | null) => {
    setLanguages(value ? [value] : ["en"]);
  };

  const handleAutoGeneratedChange = (checked: boolean) => {
    setIncludeAutoGenerated(checked);
  };

  if (subtitleType === "none") {
    return null;
  }

  return (
    <div className="space-y-3 p-3 rounded-lg bg-secondary/30 border border-border">
      <div className="space-y-2">
        <Label htmlFor="subtitle-type" className="text-sm">
          Subtitle Handling
        </Label>
        <Select value={subtitleType} onValueChange={handleSubtitleTypeChange}>
          <SelectTrigger id="subtitle-type" className="h-8 text-xs">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="none">None</SelectItem>
            <SelectItem value="external">External (separate file)</SelectItem>
            <SelectItem value="burned">Burned (embedded in video)</SelectItem>
          </SelectContent>
        </Select>
      </div>

      <div className="space-y-2">
        <Label htmlFor="subtitle-lang" className="text-sm">
          Language
        </Label>
        <Select value={languages[0] || "en"} onValueChange={handleLanguageChange}>
          <SelectTrigger id="subtitle-lang" className="h-8 text-xs">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            {SUBTITLE_LANGUAGES.map((lang) => (
              <SelectItem key={lang.value} value={lang.value}>
                {lang.label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      <div className="flex items-center justify-between">
        <Label htmlFor="auto-gen" className="text-sm">
          Include Auto-Generated
        </Label>
        <Switch
          id="auto-gen"
          checked={includeAutoGenerated}
          onCheckedChange={handleAutoGeneratedChange}
        />
      </div>
    </div>
  );
};
